# general metadata
version: "0.0.1"
repository: "git@github.com:elastic/ent-search-connectors.git"
revision: "39980fac598996d841ace42b281499e4cf32647d"
# web service
http:
  port: 9292
  raise_errors: true
  show_exceptions: false
  api_key: secret
  deactivate_auth: true
