# general metadata
version: "0.0.1"
repository: "https://github.com/elastic/connectors"
revision: "main"
# web service
http:
  port: 9292
  raise_errors: true
  show_exceptions: false
  api_key: 71BBF1DD77014462BCA9CDFDA40A128E
