# general metadata
version: "8.2.0-SNAPSHOT"
repository: "https://github.com/elastic/connectors"
revision: "main"

# web service
http:
  port: 9292
  raise_errors: true
  show_exceptions: false
  api_key: secret
  deactivate_auth: true
  connector: share_point
